// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRBWhLvEPAszHiNCSG1DvwH9HqUt9dEpE',
    appId: '1:116664638248:web:2aece19fd00907a1984e1d',
    messagingSenderId: '116664638248',
    projectId: 'quicktable-424dd',
    authDomain: 'quicktable-424dd.firebaseapp.com',
    storageBucket: 'quicktable-424dd.firebasestorage.app',
    measurementId: 'G-3RBE0NP46J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIobo4Ai7xT3OTdvilLjPo2R2jvHa97zo',
    appId: '1:116664638248:android:2f1ca4a3901ead8e984e1d',
    messagingSenderId: '116664638248',
    projectId: 'quicktable-424dd',
    storageBucket: 'quicktable-424dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Updymfy_FReX5wZ6bZ0zxhLMmTsMUgs',
    appId: '1:116664638248:ios:b92320d0656aef12984e1d',
    messagingSenderId: '116664638248',
    projectId: 'quicktable-424dd',
    storageBucket: 'quicktable-424dd.firebasestorage.app',
    iosBundleId: 'com.example.quicktable',
  );
}
